version: '2'

services:
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./:/var/www/html/wp-content/themes/javascript-2099
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: "true"

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
